// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJl6Zdc-Ad6O3BJfOKHZ0OMKOMBaK1m4A',
    appId: '1:802859136599:web:a8f7e01529715b94f5d512',
    messagingSenderId: '802859136599',
    projectId: 'my-notes-project-49fb8',
    authDomain: 'my-notes-project-49fb8.firebaseapp.com',
    databaseURL: 'https://my-notes-project-49fb8-default-rtdb.firebaseio.com',
    storageBucket: 'my-notes-project-49fb8.appspot.com',
    measurementId: 'G-PDM5DQFE9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClAqQMS329kI_nKSQP2fVsSGpdIqOHyFM',
    appId: '1:802859136599:android:a11dc79bfc7c0894f5d512',
    messagingSenderId: '802859136599',
    projectId: 'my-notes-project-49fb8',
    databaseURL: 'https://my-notes-project-49fb8-default-rtdb.firebaseio.com',
    storageBucket: 'my-notes-project-49fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQtWZYc3aiBLJq5_6-OvgGfWjqpCY3iQ',
    appId: '1:802859136599:ios:750109251cd78128f5d512',
    messagingSenderId: '802859136599',
    projectId: 'my-notes-project-49fb8',
    databaseURL: 'https://my-notes-project-49fb8-default-rtdb.firebaseio.com',
    storageBucket: 'my-notes-project-49fb8.appspot.com',
    iosClientId: '802859136599-ainalubc9gahmbemedhaut7tik4k0v9k.apps.googleusercontent.com',
    iosBundleId: 'com.SowadRafi.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQtWZYc3aiBLJq5_6-OvgGfWjqpCY3iQ',
    appId: '1:802859136599:ios:750109251cd78128f5d512',
    messagingSenderId: '802859136599',
    projectId: 'my-notes-project-49fb8',
    databaseURL: 'https://my-notes-project-49fb8-default-rtdb.firebaseio.com',
    storageBucket: 'my-notes-project-49fb8.appspot.com',
    iosClientId: '802859136599-ainalubc9gahmbemedhaut7tik4k0v9k.apps.googleusercontent.com',
    iosBundleId: 'com.SowadRafi.myNotes',
  );
}
